FROM golang:1.23.2-alpine3.20 AS builder
RUN apk update && apk add curl
RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin v1.61.0
WORKDIR /app
ENTRYPOINT golangci-lint run
